# ============================================================================
# SDC Timing Constraints - RHS2116 Single-Wire Link
# ============================================================================
# Target: MAX 10 FPGA
# Clocks: 3 domains (64MHz SPI, 100MHz system, 200MHz link)
# Design: Conservative 446kS/s, 50Mbps Manchester, 4x oversampling
# ============================================================================

# ============================================================================
# Clock definitions
# ============================================================================

# Board oscillator (external reference)
create_clock -name clk_osc -period 20.000 [get_ports {clk_osc}]

# PLL outputs
# Note: These will be generated by Quartus PLL IP
# Periods calculated from 50MHz reference

create_clock -name clk_spi  -period 15.625 [get_clocks {pll0|clk_spi}]   ;# 64MHz
create_clock -name clk_sys  -period 10.000 [get_clocks {pll0|clk_sys}]   ;# 100MHz
create_clock -name clk_link -period 5.000  [get_clocks {pll0|clk_link}]  ;# 200MHz

# ============================================================================
# Clock groups (asynchronous)
# ============================================================================
# Mark cross-clock-domain paths as asynchronous to disable timing analysis
# CDC is handled by gray-code pointers and double flip-flop sync chains

# clk_link (200MHz) and clk_sys (100MHz) treated as async
# Even though they share PLL source, we want strict CDC through FIFO only
set_clock_groups -asynchronous \
    -group [get_clocks {clk_link}] \
    -group [get_clocks {clk_sys}]

# clk_spi is independent from clk_sys (separate PLL)
set_clock_groups -asynchronous \
    -group [get_clocks {clk_spi}] \
    -group [get_clocks {clk_sys}]

# ============================================================================
# SPI input synchronization (false path)
# ============================================================================
# SPI control signals (enable) are synchronized with 2-stage sync chain
# The sync chain itself is protected by ASYNC_REG, but the path TO it
# needs false path to prevent timing analysis

# These paths have ASYNC_REG protection but are still analyzed for setup/hold
# Add false path to prevent unrealistic timing requirements
set_false_path -from [get_clocks {clk_sys}] \
               -to [get_registers {spi_master_rhs2116:*|enable_spi*}] \
               -comment "Enable sync chain input treated as async"

# ============================================================================
# CDC synchronization chain protection
# ============================================================================
# Protect double flip-flop synchronizers from optimization
# These registers MUST NOT be moved or optimized

# Async FIFO 200M->100M - read pointer sync to write domain
set_instance_assignment -name ASYNC_REG ON \
    -to "rhs2116_link_decoder:u_decoder|async_fifo_200to100:u_async_fifo|rd_gray_wr1"
set_instance_assignment -name ASYNC_REG ON \
    -to "rhs2116_link_decoder:u_decoder|async_fifo_200to100:u_async_fifo|rd_gray_wr2"

# Async FIFO 200M->100M - write pointer sync to read domain
set_instance_assignment -name ASYNC_REG ON \
    -to "rhs2116_link_decoder:u_decoder|async_fifo_200to100:u_async_fifo|wr_gray_rd1"
set_instance_assignment -name ASYNC_REG ON \
    -to "rhs2116_link_decoder:u_decoder|async_fifo_200to100:u_async_fifo|wr_gray_rd2"

# Frame Packer FIFO - SPI 64M to System 100M
set_instance_assignment -name ASYNC_REG ON \
    -to "rhs2116_link_encoder:u_encoder|frame_packer_100m:u_frame_packer|async_fifo_200to100:u_async_fifo|rd_gray_wr1"
set_instance_assignment -name ASYNC_REG ON \
    -to "rhs2116_link_encoder:u_encoder|frame_packer_100m:u_frame_packer|async_fifo_200to100:u_async_fifo|rd_gray_wr2"
set_instance_assignment -name ASYNC_REG ON \
    -to "rhs2116_link_encoder:u_encoder|frame_packer_100m:u_frame_packer|async_fifo_200to100:u_async_fifo|wr_gray_rd1"
set_instance_assignment -name ASYNC_REG ON \
    -to "rhs2116_link_encoder:u_encoder|frame_packer_100m:u_frame_packer|async_fifo_200to100:u_async_fifo|wr_gray_rd2"

# SPI output sync back to clk_sys
set_instance_assignment -name ASYNC_REG ON \
    -to "spi_master_rhs2116:*|data_valid_sync1"
set_instance_assignment -name ASYNC_REG ON \
    -to "spi_master_rhs2116:*|data_out_sync1"

# ============================================================================
# Max delay constraints (within same clock domain)
# ============================================================================
# Constrain FIFO pointer logic to prevent excessive logic levels
# These are within SAME clock domain after gray-binary conversion

# 200MHz domain: Gray-to-binary conversion (must be < 4ns)
set_max_delay -from [get_registers {*clk_link* *wr_ptr_gray*}] \
              -to [get_registers {*clk_link* *wr_ptr_bin*}] \
              4.0 \
              -comment "FIFO write pointer conversion (200MHz)"

set_max_delay -from [get_registers {*clk_link* *rd_ptr_gray*}] \
              -to [get_registers {*clk_link* *rd_ptr_bin*}] \
              4.0 \
              -comment "FIFO read pointer conversion (200MHz)"

# 100MHz domain: CRC calculation (10ns available)
set_max_delay -from [get_registers {*frame_packer_100m* *shift_reg*}] \
              -to [get_registers {*frame_packer_100m* *tx_bit*}] \
              8.0 \
              -comment "Frame packer critical path (100MHz)"

# ============================================================================
# Input/output delays (board-level timing)
# ============================================================================
# These account for PCB trace delays and external setup/hold times
# Adjust based on actual board layout

# Manchester input (from coax connector)
set_input_delay -clock clk_link -max 2.0 [get_ports {manch_in}] \
                -comment "2ns PCB trace delay + margin"

# Manchester DDR outputs (to coax connector)
set_output_delay -clock clk_sys -max 1.5 [get_ports {ddr_p ddr_n}] \
                 -comment "1.5ns output delay to meet IOB timing"

# SPI outputs
set_output_delay -clock clk_spi -max 1.5 [get_ports {cs_n sclk mosi}] \
                 -comment "SPI output timing"

# SPI input (MISO)
set_input_delay -clock clk_spi -max 2.0 [get_ports {miso}] \
                -comment "MISO input timing"

# ============================================================================
# Physical synthesis optimizations
# ============================================================================
# Force critical registers into IOB for best timing

# Manchester DDR outputs (must be in IOB to use DDR)
set_instance_assignment -name FAST_OUTPUT_REGISTER ON \
    -to [get_ports {ddr_p ddr_n}]
set_instance_assignment -name IO_REGISTER ON \
    -to [get_ports {ddr_p ddr_n}]

# CDR input (minimize input buffer to first flop delay)
set_instance_assignment -name FAST_INPUT_REGISTER ON \
    -to [get_ports {manch_in}]

# SPI pins
set_instance_assignment -name IO_REGISTER ON \
    -to [get_ports {cs_n sclk mosi miso}]

# ============================================================================
# Maximum fanout constraints
# ============================================================================
# Prevent high fanout nets that cause routing delays

set_max_fanout 16 [get_clocks {clk_link}]   ;# 200MHz domain - keep low
set_max_fanout 32 [get_clocks {clk_sys}]    ;# 100MHz domain - moderate
set_max_fanout 48 [get_clocks {clk_spi}]    ;# 64MHz domain - can be higher

# ============================================================================
# Timing exceptions (valid multi-cycle paths)
# ============================================================================
# None - this design has no intentional multi-cycle paths
# All logic should complete in single cycle

# ============================================================================
# Derating and uncertainty (conservative)
# ============================================================================
# Account for temperature, voltage, and process variation

set_timing_derate -late -multiply_by 1.05 [get_clock_info]
set_timing_derate -early -multiply_by 0.95 [get_clock_info]

set_clock_uncertainty -setup 0.5 [get_clocks {clk_link}]
set_clock_uncertainty -setup 0.3 [get_clocks {clk_sys}]
set_clock_uncertainty -setup 0.4 [get_clocks {clk_spi}]

# ============================================================================
# Optimization targets
# ============================================================================
# Use adaptive Logic Module (ALM) packing for best area/timing

set_global_assignment -name OPTIMIZATION_TECHNIQUE SPEED
set_global_assignment -name AUTO_RESOURCE_SHARING OFF
set_global_assignment -name ALLOW_REGISTER_MERGING OFF

# Suppress warnings about unused status outputs
# (during development, not all status signals may be connected)
set_global_assignment -name MESSAGE_DISABLE 18152  ;# Unused output
set_global_assignment -name MESSAGE_DISABLE 10492  ;# Unused pin

# ============================================================================
# EOF
# ============================================================================
